"""user and user_attributes table made

Revision ID: fc14382c7ba1
Revises: 
Create Date: 2023-03-27 11:21:20.952178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc14382c7ba1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User Attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interests', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('astrology', sa.String(), nullable=True),
    sa.Column('drinking', sa.NullType(), nullable=True),
    sa.Column('smoking', sa.NullType(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borough', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('User Location')
    op.drop_table('User Attributes')
    # ### end Alembic commands ###
